### ISSUE TITLE
Build & Publish actions

### ISSUE THREAD

**Issue by binyamin555** [xpodev/extype#10]
It would make our lives easier if we make it so whenever there's a merge to the main branch, it'll build the package and run the tests.

Also, if possible, whenever we create a release, also upload it to PyPI

**Comment by elazarcoh** [comment]
reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by neriyaco** [comment]
I believe this PR #11 fixed this issue
