### ISSUE TITLE
Add built-in extensions

### ISSUE THREAD

**Issue by binyamin555** [xpodev/extype#19]
It may be thought of as part of #13 in the sense that each extension type should be applied separately.

So users can do:
```py
from extype import extensions

extensions.apply()  # all
extensions.apply(list, int)  # only for int & list
```

I don't know if it's the best idea, so you should also suggest the way you think is best to do this.

**Comment by elazarcoh** [comment]
```python
# builtins_extension

def extend_list(): ...

#user code
from extype import builtins_extension

builtins_extension.extend_list().all()
# or
builtins_extension.extend_list().reduce().map()
```

**Comment by elazarcoh** [comment]
@binyamin555 @neriyaco suggest more ideas, let's brainstorm it. Maybe given lots of ideas we get a good UX.

**Comment by binyamin555** [comment]
```
# builtins_extension

def extend(typ: type): ...

# user code
from extype import builtins_extension

[*builtins_extension.extend(list)]  # what if 'all' is an extension?
# or
builtins_extension.extend(list).reduce().map()
```

**Comment by binyamin555** [comment]
> @binyamin555 @neriyaco suggest more ideas, let's brainstorm it. Maybe given lots of ideas we get a good UX.

Sounds like something an AI would say...

**Comment by binyamin555** [comment]
In any case, I guess we all agree that built-in extensions should be separated from the other things.

Now, we have 2 options to go with:
1) Make a subdirectory named `builtin_extensions` for built-in extensions (i.e. a sub module / sub package)
2) Have all built-in extensions in a single file named `builtin_extensions.py`

What do you think? Once we know about that I can progress with making the source directory more organized.
@neriyaco @elazarcoh

**Comment by neriyaco** [comment]
I'd put it in a separate folder.

**Comment by binyamin555** [comment]
> I think a folder with numbers.py, iterable.py etc.
> and `__init__.py` will expose the most relevant functions

That may become very uncomfortable. Say, I want to extend list only.
```py
from extypes.builtin_extensions import list

list.extend()  # huh?

x = list()  # error??
```

**Comment by elazarcoh** [comment]
yeah fine then another names.
exlist?

**Comment by elazarcoh** [comment]
I tried to toy with typing a bit. I think it'll be easier to implement the typing in stubs.
Maybe we can find a way to override the builtins stubs, see [pep 561](https://peps.python.org/pep-0561/#type-checker-module-resolution-order) for the stubs resolution order, and [Typeshed](https://github.com/python/typeshed/tree/main/stdlib) for builtins stubs.

**Comment by binyamin555** [comment]
Just putting some extensions we might want to add:

```py
# int
int.hex()
int.octal()
int.bin()

# float
float.round()

# lazy sequences
map.tolist()
filter.tolist()

# list
list.any((any -> bool) | None = bool)
list.all((any -> bool) | None = bool)

# dict
dict.__add__(dict)  # dict + dict
dict.join((a, b) -> a | b
```

**Comment by binyamin555** [comment]
I have omitted `dict` extensions because they felt a bit weird.

**Comment by elazarcoh** [comment]
I agree. I think that we should add extensions to dictkeys and dictvalues, same as list. probably should return a tuple rather than dictkeys, though.

**Comment by binyamin555** [comment]
I did not get what you mean. Care to explain via code (plz)?

**Comment by elazarcoh** [comment]
`type({}.keys())` etc.

**Comment by binyamin555** [comment]
oh, so you can manipulate `dictkeys` and `dictvalues` as if they were lists?

**Comment by elazarcoh** [comment]
yes

**Comment by binyamin555** [comment]
Well, what should `dict_keys.map` return? `list? (also for the other types)

**Comment by elazarcoh** [comment]
not sure. tuple?

**Comment by binyamin555** [comment]
I think that homogenous type would be better, so a list (since keys "should" be of the same type)
