### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Meiserj** [xpodev/extype#28]
When installed via pip on Python 3.9 and 3.11 on Windows trying to call `from extype import extension, extend_type_with` I get this message: `ImportError: DLL load failed while importing core: The module was not found.` I tried 2 reinstalls on each version with no change.

While trying to install from git with `pip install git+https://github.com/xpodev/extype` I get this error
```
The Meson build system
      [...]
      Build type: native build
      Project name: extype
      Project version: 1.0.0
      C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.28
      Host machine cpu family: x86
      Host machine cpu: x86
      Program python found: YES
      Need python for x86, but found x86_64
      Run-time dependency python found: NO (tried sysconfig)
```

**Comment by binyamin555** [comment]
Hi. 
Is your machine 32 or 64 bit? We currently only support 64-bit, but I'll look into adding support for 32-bit as well.

**Comment by Meiserj** [comment]
It is a 64bit system. It finds the x86_64 python, but seems to only want x86?

**Comment by binyamin555** [comment]
I can't seem to reproduce the error when installing from GitHub. 

I am working on pip though, trying to make this work.

**Comment by Meiserj** [comment]
I haven't tried it in a venv yet. Maybe that works. On another note: I'm not that familiar with python interfaces which core.pyi seems to be. Where are the methods you set there implemented?

**Comment by binyamin555** [comment]
Those methods are more for internal use as they deal with the internal structure of Python objects in the C side of Python.
As such, they are not intended for use by users. We might add another layer over them in the future so they can be used by consumers.

**Comment by elazarcoh** [comment]
Reopening just to make sure it's solved. @Meiserj can you verify?

**Comment by Meiserj** [comment]
No, both pip install extype and the git install still throw the same errors described in my first message

**Comment by elazarcoh** [comment]
Can you post the output of `python -V` and `pip freeze` (to get the installed version of extype), so we can try to reproduce?

**Comment by elazarcoh** [comment]
BTW I won't put too much effort in installing from git, as it tries from source, which needs some additional setup (e.g. MSVC on windows). If you want to get into it we can help debug the build issue, but preferably let's just figure out the installation from pypi issue, which will be more relevant to most users.

**Comment by binyamin555** [comment]
We're having some problems with the GitHub publish workflow... The Windows .whl files are built incorrectly.

**Comment by binyamin555** [comment]
Ok, this should work now. @Meiserj can you confirm?

**Comment by Meiserj** [comment]
I use this code to test:
```
from extype import extension, extend_type_with

@extension(str)
class StringExtension(str):
    def hello(self):
        return "Hello " + self
    
extend_type_with(str, StringExtension)

print("Hello World".hello())
```

And now get this error: 
```
Traceback (most recent call last):
  File "c:\test.py", line 3, in <module>
    @extension(str)
     ^^^^^^^^^^^^^^
TypeError: 'ExtensionObject' object is not callable
```

**Comment by binyamin555** [comment]
As the readme states, you should use the `extension` decorator on the functions themselves.

```
from extype import extension, extend_type_with

class StringExtension(str):
    @extension
    def hello(self):
        return "Hello " + self
    
extend_type_with(str, StringExtension)

print("Hello World".hello())
```

**Comment by Meiserj** [comment]
`python -V` says my venv is on version `3.11.0`
`pip freeze` produces only `extype==1.1.1`

**Comment by Meiserj** [comment]
Your code snipped produces the same error, except now it is on line 5 (since the @extension call moved)

**Comment by binyamin555** [comment]
Can you send the code you have now? If you have `()` after the `@extension`, you should remove it.

**Comment by Meiserj** [comment]
Nevermind, I forgot to remove the `(str)`. Now it works, thank you!
